- hosts: Cat3750
  gather_facts: no

  tasks:
    - name: send show clock
      ios_command:
        commands: "show clock"
      register: ios_results
    - name: display show clock
      debug:
        var: ios_results
